---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  selector:
    app: simpleapp
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: simpleapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      name: simpleapp
      labels:
        app: simpleapp
    spec:
      containers:
        - name: app
          image: "fair18/simpleapp:0.0.1"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 10
  selector:
    matchLabels:
      app: simpleapp
...
